import Head from "next/head";
import Image from "next/image";
import { Inter, Noto_Sans_Mongolian } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });
import ContactUs from "./components/ContactUs";

let audio = null;
if (typeof window !== "undefined") {
  audio = new Audio("kizomba.mp3");
  //audio = new Audio("https://firebasestorage.googleapis.com/v0/b/chantantoine-99e5c.appspot.com/o/Camelia-Jordana-Non-Non-Non.mp3?alt=media&amp;token=2b1cdfde-39b1-4b4e-bd04-4ea68a3fbff1")
}
function start() {
  audio?.play();
}

function stop() {
  audio?.pause();
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.big}>Venha dançar no Paraíso</div>
        <br></br>
        <div style={{ color: "yellow" }}>
          Para reservar ligue para Pat: 012325854
        </div>
        <br></br>
        <Image
          src="/IMG_20221031_091102.jpg"
          alt="Vercel Logo"
          className={styles.vercelLogo}
          width={500}
          height={375}
          priority
        />
        <br></br>
        <Image
          src="/IMG_20221031_091535.jpg"
          alt="Vercel Logo"
          className={styles.vercelLogo}
          width={500}
          height={375}
          priority
        />
        <button className={styles.boutonright} onClick={start}>
          toque a música
        </button>
        <button className={styles.boutonleft} onClick={stop}>
          pare a música
        </button>
        <br></br>
        <p className={styles.description} style={{ color: "yellow" }}>
          Não é apropriado sugerir que o objetivo principal de sua visita ao
          Paradiso é pegar mulheres. O Paradiso é um local de entretenimento e
          lazer, sendo importante respeitar as demais pessoas que ali estão
          presentes e não tentar incomodá-las de forma alguma. Se você deseja
          socializar e conhecer novas pessoas, é recomendável que o faça de
          maneira respeitosa e atenciosa.
        </p>

        <br></br>
        {/*

          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
         

  */}

        <p>
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3206.5171466687357!2d13.277442314786816!3d-9.048410993507366!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x66ec6242a1c44de!2zOcKwMDInNTQuMyJTIDEzwrAxNic0Ni43IkU!5e1!3m2!1sfr!2sfr!4v1673114649083!5m2!1sfr!2sfr"
            width="500"
            height="375"
            style={{ marginRight: "em" }}
            allowFullScreen=""
            loading="lazy"
            referrerPolicy="no-referrer-when-downgrade"
          ></iframe>
        </p>

        {/*
        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
 




  
 {/*          <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
<h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
  
          </a>
        </div>

*/}
        <br></br>
        <ContactUs />
      </main>
    </>
  );
}
