import Head from 'next/head'
import Image from 'next/image'
import { Inter, Noto_Sans_Mongolian } from '@next/font/google'
import styles from '../styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })


const audioo = new Audio("audios.mp3")
//const audioo = new Audio("https://firebasestorage.googleapis.com/v0/b/chantantoine-99e5c.appspot.com/o/Camelia-Jordana-Non-Non-Non.mp3?alt=media&amp;token=2b1cdfde-39b1-4b4e-bd04-4ea68a3fbff1")

function start() {
audioo.play();
}

function stop() {
audioo.pause();
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

     
      <main className={styles.main}>
        <div className={styles.description}>
          
<h1>


<p>
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d121.48648106135077!2d2.327856907340246!3d48.88498590000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1sfr!2sfr!4v1672687372634!5m2!1sfr!2sfr" width="600" height="450" style={{marginRight:  'em'}} allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</p>
          
          <Image
                src="/Bredele.jpg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={1000}
                height={1000}
                priority

                
              />

<button className= {styles.boutonright} onClick={start}>
Lance la musique
</button>

<button className={styles.boutonleft} onClick={stop}>
Stoppe la musique
</button>
  

</h1>




{/*

          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>

  */}

        </div>

        <div className={styles.big} >
          
          Venez danser au Paradiso
        
        </div>

        
        
{/*
        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
 




  
 {/*          <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
<h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
  
          </a>
        </div>

*/}


      </main>
    </>
  )
}
